export const ADD_POKEMONS = "ADD_POKEMONS";
export const ADD_POKEMONS_TYPES = "ADD_POKEMONS_TYPES";
export const ADD_POKEMON_INFO = "ADD_POKEMON_INFO";
export const ADD_ALL_TYPES_POKEMON = "ADD_ALL_TYPES_POKEMON";
export const ADD_FOUND_POKEMON = "ADD_FOUND_POKEMON";
